[2025-05-10 21:42:36,342] ERROR django.request (log): Internal Server Error: /bibliothecaire/gestion-des-medias/
Traceback (most recent call last):
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\contrib\sessions\backends\base.py", line 244, in _get_session
    return self._session_cache
           ^^^^^^^^^^^^^^^^^^^
AttributeError: 'SessionStore' object has no attribute '_session_cache'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\db\backends\base\base.py", line 279, in ensure_connection
    self.connect()
    ~~~~~~~~~~~~^^
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\db\backends\base\base.py", line 256, in connect
    self.connection = self.get_new_connection(conn_params)
                      ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\db\backends\mysql\base.py", line 256, in get_new_connection
    connection = Database.connect(**conn_params)
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\MySQLdb\__init__.py", line 121, in Connect
    return Connection(*args, **kwargs)
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\MySQLdb\connections.py", line 200, in __init__
    super().__init__(*args, **kwargs2)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
MySQLdb.OperationalError: (2002, "Can't connect to server on 'localhost' (10061)")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\contrib\auth\decorators.py", line 57, in _view_wrapper
    test_pass = test_func(request.user)
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\contrib\auth\decorators.py", line 80, in <lambda>
    lambda u: u.is_authenticated,
              ^^^^^^^^^^^^^^^^^^
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\utils\functional.py", line 251, in inner
    self._setup()
    ~~~~~~~~~~~^^
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\utils\functional.py", line 404, in _setup
    self._wrapped = self._setupfunc()
                    ~~~~~~~~~~~~~~~^^
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\contrib\auth\middleware.py", line 37, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
                                            ~~~~~~~~^^^^^^^^^
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\contrib\auth\middleware.py", line 17, in get_user
    request._cached_user = auth.get_user(request)
                           ~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\contrib\auth\__init__.py", line 209, in get_user
    user_id = _get_user_session_key(request)
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\contrib\auth\__init__.py", line 62, in _get_user_session_key
    return get_user_model()._meta.pk.to_python(request.session[SESSION_KEY])
                                               ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\contrib\sessions\backends\base.py", line 55, in __getitem__
    return self._session[key]
           ^^^^^^^^^^^^^
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\contrib\sessions\backends\base.py", line 249, in _get_session
    self._session_cache = self.load()
                          ~~~~~~~~~^^
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\contrib\sessions\backends\db.py", line 55, in load
    s = self._get_session_from_db()
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\contrib\sessions\backends\db.py", line 34, in _get_session_from_db
    return self.model.objects.get(
           ~~~~~~~~~~~~~~~~~~~~~~^
        session_key=self.session_key, expire_date__gt=timezone.now()
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\db\models\query.py", line 645, in get
    num = len(clone)
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\db\models\query.py", line 382, in __len__
    self._fetch_all()
    ~~~~~~~~~~~~~~~^^
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\db\models\query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size
    )
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1572, in execute_sql
    cursor = self.connection.cursor()
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\db\backends\base\base.py", line 320, in cursor
    return self._cursor()
           ~~~~~~~~~~~~^^
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\db\backends\base\base.py", line 296, in _cursor
    self.ensure_connection()
    ~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\db\backends\base\base.py", line 278, in ensure_connection
    with self.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\db\backends\base\base.py", line 279, in ensure_connection
    self.connect()
    ~~~~~~~~~~~~^^
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\db\backends\base\base.py", line 256, in connect
    self.connection = self.get_new_connection(conn_params)
                      ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\db\backends\mysql\base.py", line 256, in get_new_connection
    connection = Database.connect(**conn_params)
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\MySQLdb\__init__.py", line 121, in Connect
    return Connection(*args, **kwargs)
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\MySQLdb\connections.py", line 200, in __init__
    super().__init__(*args, **kwargs2)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: (2002, "Can't connect to server on 'localhost' (10061)")
[2025-05-10 21:42:36,438] ERROR django.server (basehttp): "GET /bibliothecaire/gestion-des-medias/ HTTP/1.1" 500 145
[2025-05-10 21:42:59,189] ERROR django.request (log): Internal Server Error: /
Traceback (most recent call last):
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\contrib\sessions\backends\base.py", line 244, in _get_session
    return self._session_cache
           ^^^^^^^^^^^^^^^^^^^
AttributeError: 'SessionStore' object has no attribute '_session_cache'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\db\backends\base\base.py", line 279, in ensure_connection
    self.connect()
    ~~~~~~~~~~~~^^
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\db\backends\base\base.py", line 256, in connect
    self.connection = self.get_new_connection(conn_params)
                      ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\db\backends\mysql\base.py", line 256, in get_new_connection
    connection = Database.connect(**conn_params)
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\MySQLdb\__init__.py", line 121, in Connect
    return Connection(*args, **kwargs)
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\MySQLdb\connections.py", line 200, in __init__
    super().__init__(*args, **kwargs2)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
MySQLdb.OperationalError: (2002, "Can't connect to server on 'localhost' (10061)")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\mediatheque_app\views.py", line 4, in homepage
    return render(request, 'homePage.html')
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\template\loader_tags.py", line 210, in render
    return template.render(context)
           ~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\template\base.py", line 173, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\template\defaulttags.py", line 320, in render
    match = condition.eval(context)
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\template\defaulttags.py", line 886, in eval
    return self.value.resolve(context, ignore_failures=True)
           ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\template\base.py", line 718, in resolve
    obj = self.var.resolve(context)
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\template\base.py", line 850, in resolve
    value = self._resolve_lookup(context)
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\template\base.py", line 883, in _resolve_lookup
    current = current[bit]
              ~~~~~~~^^^^^
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\utils\functional.py", line 251, in inner
    self._setup()
    ~~~~~~~~~~~^^
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\utils\functional.py", line 404, in _setup
    self._wrapped = self._setupfunc()
                    ~~~~~~~~~~~~~~~^^
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\contrib\auth\middleware.py", line 37, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
                                            ~~~~~~~~^^^^^^^^^
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\contrib\auth\middleware.py", line 17, in get_user
    request._cached_user = auth.get_user(request)
                           ~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\contrib\auth\__init__.py", line 209, in get_user
    user_id = _get_user_session_key(request)
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\contrib\auth\__init__.py", line 62, in _get_user_session_key
    return get_user_model()._meta.pk.to_python(request.session[SESSION_KEY])
                                               ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\contrib\sessions\backends\base.py", line 55, in __getitem__
    return self._session[key]
           ^^^^^^^^^^^^^
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\contrib\sessions\backends\base.py", line 249, in _get_session
    self._session_cache = self.load()
                          ~~~~~~~~~^^
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\contrib\sessions\backends\db.py", line 55, in load
    s = self._get_session_from_db()
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\contrib\sessions\backends\db.py", line 34, in _get_session_from_db
    return self.model.objects.get(
           ~~~~~~~~~~~~~~~~~~~~~~^
        session_key=self.session_key, expire_date__gt=timezone.now()
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\db\models\query.py", line 645, in get
    num = len(clone)
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\db\models\query.py", line 382, in __len__
    self._fetch_all()
    ~~~~~~~~~~~~~~~^^
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\db\models\query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size
    )
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1572, in execute_sql
    cursor = self.connection.cursor()
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\db\backends\base\base.py", line 320, in cursor
    return self._cursor()
           ~~~~~~~~~~~~^^
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\db\backends\base\base.py", line 296, in _cursor
    self.ensure_connection()
    ~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\db\backends\base\base.py", line 278, in ensure_connection
    with self.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\db\backends\base\base.py", line 279, in ensure_connection
    self.connect()
    ~~~~~~~~~~~~^^
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\db\backends\base\base.py", line 256, in connect
    self.connection = self.get_new_connection(conn_params)
                      ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\db\backends\mysql\base.py", line 256, in get_new_connection
    connection = Database.connect(**conn_params)
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\MySQLdb\__init__.py", line 121, in Connect
    return Connection(*args, **kwargs)
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\MySQLdb\connections.py", line 200, in __init__
    super().__init__(*args, **kwargs2)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: (2002, "Can't connect to server on 'localhost' (10061)")
[2025-05-10 21:42:59,253] ERROR django.server (basehttp): "GET / HTTP/1.1" 500 145
